FROM elbromasmc/final-exam

# Run application in development mode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create and change to non-root user
RUN groupadd --gid $USER_GID devrunner \
    && useradd --uid $USER_UID --gid $USER_GID -m devrunner

# Change to non-root user and enter home directory
USER devrunner
WORKDIR /home/devrunner

# Create and enter src folder
RUN mkdir /home/devrunner/src
WORKDIR /home/devrunner/src
VOLUME /home/devrunner/src

ENTRYPOINT ["/bin/bash"]
